export const SET_POLISH_EXAM_POINTS = "SET_POLISH_EXAM_POINTS";
export const SET_MATHEMATICS_EXAM_POINTS = "SET_MATHEMATICS_EXAM_POINTS";
export const SET_ENGLISH_EXAM_POINTS = "SET_ENGLISH_EXAM_POINTS";

export const SET_POLISH_GRADE = "SET_POLISH_GRADE";
export const SET_FIRST_GRADE = "SET_FIRST_GRADE";
export const SET_MATHEMATICS_GRADE = "SET_MATHEMATICS_GRADE";
export const SET_SECOND_GRADE = "SET_SECOND_GRADE";

export const SET_RED_STRIPE = "SET_RED_STRIPE";
export const SET_VOLOUNTEERING = "SET_VOLOUNTEERING";

export const SET_COMPETITIONS = "SET_COMPETITIONS";
